job:
  package-manager: npm_and_yarn
  allowed-updates:
    - dependency-type: direct
      update-type: all
  dependencies:
    - "@babel/plugin-transform-modules-systemjs"
  security-advisories:
    - dependency-name: "@babel/plugin-transform-modules-systemjs"
      affected-versions:
        - ">= 7.12.0 <= 7.29.3"
        - ">= 8.0.0-alpha.0 <= 8.0.0-alpha.12"
      patched-versions: []
      unaffected-versions: []
  security-updates-only: true
  repo-private: false
  source:
    provider: github
    repo: Swampen/turborepo-poc
    directory: /
    commit: 7d213491afab509a9b171dee94bd4f00d134bc17
